#! /usr/bin/env bash
set -e

# vii-core
wget -O vii-core http://arthurzq.oicp.io:3501/vii-app/vii-core
mv vii-core /usr/bin
chmod +x /usr/bin/vii-core

# horizon
wget -O vii-horizon http://arthurzq.oicp.io:3501/vii-app/vii-horizon
mv vii-horizon /usr/bin
chmod +x /usr/bin/vii-horizon

echo "\nDone installing vii-core and horizon...\n"
